import pandas as pd
from sqlalchemy import create_engine, Column, Integer, String, Float, ForeignKey
from sqlalchemy.orm import declarative_base, relationship

# 1. Setup SQLite Database Connection
db_file = '../data/movies.db'
engine = create_engine(f'sqlite:///{db_file}', echo=False)
Base = declarative_base()


# 2. Define SQLAlchemy ORM Models
class Movie(Base):
    __tablename__ = 'movies'

    # Primary Key matches CSV
    movieId = Column(Integer, primary_key=True)
    title = Column(String)
    genres = Column(String)

    # Relationships to other tables
    links = relationship("Link", back_populates="movie", uselist=False)
    ratings = relationship("Rating", back_populates="movie")
    tags = relationship("Tag", back_populates="movie")


class Link(Base):
    __tablename__ = 'links'

    # movieId is both PK and FK (One-to-One with Movie)
    movieId = Column(Integer, ForeignKey('movies.movieId'), primary_key=True)
    imdbId = Column(Integer)
    tmdbId = Column(Float)  # Float to handle potential NaNs

    movie = relationship("Movie", back_populates="links")


class Rating(Base):
    __tablename__ = 'ratings'

    # Surrogate Primary Key (auto-incrementing)
    id = Column(Integer, primary_key=True, autoincrement=True)
    userId = Column(Integer)
    movieId = Column(Integer, ForeignKey('movies.movieId'))
    rating = Column(Float)
    timestamp = Column(Integer)

    movie = relationship("Movie", back_populates="ratings")


class Tag(Base):
    __tablename__ = 'tags'

    # Surrogate Primary Key (auto-incrementing)
    id = Column(Integer, primary_key=True, autoincrement=True)
    userId = Column(Integer)
    movieId = Column(Integer, ForeignKey('movies.movieId'))
    tag = Column(String)
    timestamp = Column(Integer)

    movie = relationship("Movie", back_populates="tags")


# 3. Create Tables in the Database
Base.metadata.create_all(engine)
print("Database schema created successfully.")


# 4. Load Data from CSV Files
def load_csv_to_DB():
    try:
        # Read CSVs into Pandas DataFrames
        df_movies = pd.read_csv('../data/movies.csv')
        df_links = pd.read_csv('../data/links.csv')
        df_ratings = pd.read_csv('../data/ratings.csv')
        df_tags = pd.read_csv('../data/tags.csv')

        # Insert data into SQL tables
        # if_exists='append' ensures we add to the tables created above
        df_movies.to_sql('movies', con=engine, if_exists='append', index=False)
        df_links.to_sql('links', con=engine, if_exists='append', index=False)

        # For Ratings and Tags, the 'id' column will be auto-generated by SQLite
        df_ratings.to_sql('ratings', con=engine, if_exists='append', index=False)
        df_tags.to_sql('tags', con=engine, if_exists='append', index=False)

        print("Data loaded successfully.")

    except FileNotFoundError as e:
        print(f"Error: {e}. Please ensure CSV files are in the given directory.")
    except Exception as e:
        print(f"An error occurred: {e}")


if __name__ == "__main__":
    load_csv_to_DB()